### PR TITLE
Readme added with multiple examples

### PR DESCRIPTION
**Pull request by nekromoff**
Since the API handling via this library is very difficult to grasp, I have added some tested examples.

### CODE REVIEW

**Comment by nekromoff** [comment]
I can add more code samples once this is merged.

**Comment by br0nhy** [comment]
Merge please

**Comment by mtx-z** [comment]
@nekromoff thanks a lot for your example. It would be great to have some more! Do you plan to do so? thanks again

**Comment by nekromoff** [comment]
I just used this one, haven't experimented with it much more.

**Comment by mtx-z** [comment]
Ah ok sorry, I thought you wanted to add more code sample. Thanks anyway.

**Comment by nekromoff** [comment]
more examples added, see my master

**Comment by bronhy** [comment]
@nekromoff i was not able to wait for spotonlive so i made this one https://github.com/bronhy/google-my-business-php-client

**Comment by nekromoff** [comment]
feel free to take my examples and merge them into your readme, just
attribute them to me.

**Comment by erhuz** [comment]
@GuardsmanPanda Merge please.

**Comment by GuardsmanPanda** [comment]
Done

**Pull request merged**
