### PR TITLE
Fixed composer.json version number

### PR DESCRIPTION
**Pull request by aprat84**
Please, as said in https://github.com/spotonlive/php-google-my-business/issues/13 and https://github.com/spotonlive/php-google-my-business/pull/12, create a `v4.4` tag and update this library at packagist.org.

More info at https://packagist.org/about

@GuardsmanPanda 
@nikolajlovenhardt 
@nekromoff

### CODE REVIEW

**Comment by nikolajlovenhardt** [comment]
@aprat84 unfortunately I’m no longer a part og this organization

**Comment by aprat84** [comment]
Didn't know. Just mentioned last "mergers" I found. Sorry!

**Comment by loeffel-io** [comment]
+1

**Comment by GuardsmanPanda** [comment]
I don't have access to the org on packagist, I think I need @nikolajlovenhardt to add me.

**Pull request merged**
